INSERT INTO company (name, slogan, credit_hold, cnpj, country, state, city, address, opn_status, ingestion_operation, status)
VALUES
('InovaTech', 'Inovação para o seu negócio', 'No', '12345678000101', 'Brasil', 'São Paulo', 'São Paulo', 'Av. Paulista, 1000', 'MEMBER', 'CSV', 'ACTIVE'),
('Alimentos Saudáveis', 'Sua saúde em primeiro lugar', 'Yes', '23456789000112', 'Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Rua das Frutas, 200', 'MEMBER', 'MANUAL', 'ACTIVE'),
('AutoPeças 2000', 'Qualidade e confiança em peças automotivas', 'No', '34567890100023', 'Brasil', 'Minas Gerais', 'Belo Horizonte', 'Av. das Indústrias, 300', 'EXPIRED', 'CSV', 'ACTIVE'),
('Consultoria Empresarial Ltda', 'Soluções inteligentes para o seu negócio', 'Yes', '45678901200034', 'Brasil', 'São Paulo', 'Campinas', 'Rua dos Negócios, 400', 'MEMBER', 'MANUAL', 'INACTIVE'),
('Construções Rápidas', 'Construindo o futuro com agilidade', 'No', '56789012300045', 'Brasil', 'Rio Grande do Sul', 'Porto Alegre', 'Av. da Construção, 500', 'MEMBER', 'CSV', 'ACTIVE'),
('Farmácia Central', 'Cuidando da sua saúde com amor', 'Yes', '67890123400056', 'Brasil', 'Rio de Janeiro', 'Niterói', 'Rua das Farmácias, 600', 'INACTIVE', 'MANUAL', 'ACTIVE'),
('Energia Solar Ltda', 'Energia limpa para um futuro sustentável', 'No', '78901234500067', 'Brasil', 'São Paulo', 'São Paulo', 'Av. da Energia, 700', 'MEMBER', 'CSV', 'ACTIVE'),
('Moda Jovem', 'Estilo e tendência para todas as idades', 'Yes', '89012345600078', 'Brasil', 'Minas Gerais', 'Belo Horizonte', 'Rua da Moda, 800', 'EXPIRED', 'MANUAL', 'INACTIVE'),
('Tecnologia Avançada S.A.', 'Inovação tecnológica para o seu dia a dia', 'No', '90123456700089', 'Brasil', 'São Paulo', 'Campinas', 'Av. da Tecnologia, 800', 'MEMBER', 'CSV', 'ACTIVE'),
('Educação Inteligente', 'Transformando conhecimento em oportunidades', 'Yes', '01234567800090', 'Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Rua da Educação, 700', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Beleza Natural', 'Respeitando a sua beleza', 'No', '12345678900010', 'Brasil', 'Paraná', 'Curitiba', 'Av. da Beleza, 600', 'INACTIVE', 'CSV', 'ACTIVE'),
('Agricultura Moderna', 'Inovação no campo para alimentar o mundo', 'Yes', '23456789000011', 'Brasil', 'São Paulo', 'São Paulo', 'Av. da Agricultura, 900', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Tecnologia da Informação Ltda', 'Transformando dados em soluções', 'No', '34567890100012', 'Brasil', 'Minas Gerais', 'Uberlândia', 'Rua da TI, 700', 'EXPIRED', 'CSV', 'ACTIVE'),
('Automotiva Nacional', 'Qualidade e confiança em cada veículo', 'Yes', '45678901200013', 'Brasil', 'São Paulo', 'Campinas', 'Av. Automotiva, 600', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Saúde em Foco', 'Cuidando da sua saúde com excelência', 'No', '56789012300014', 'Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Rua da Saúde, 800', 'MEMBER', 'CSV', 'INACTIVE'),
('Construções Sustentáveis', 'Construindo o futuro com responsabilidade', 'Yes', '67890123400015', 'Brasil', 'Minas Gerais', 'Belo Horizonte', 'Av. da Sustentabilidade, 700', 'INACTIVE', 'MANUAL', 'ACTIVE'),
('Moda Fashion', 'Estilo e elegância para todos os momentos', 'No', '78901234500016', 'Brasil', 'São Paulo', 'São Paulo', 'Av. da Moda, 900', 'MEMBER', 'CSV', 'ACTIVE'),
('Gastronomia Gourmet', 'Sabor e qualidade em cada prato', 'Yes', '89012345600017', 'Brasil', 'Rio de Janeiro', 'Niterói', 'Rua da Gastronomia, 500', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Tecnologia Aplicada', 'Soluções tecnológicas para o seu negócio', 'No', '90123456700018', 'Brasil', 'Paraná', 'Curitiba', 'Av. da Tecnologia, 700', 'EXPIRED', 'CSV', 'ACTIVE'),
('Educação Moderna', 'Transformando o aprendizado em oportunidades', 'Yes', '01234567800019', 'Brasil', 'São Paulo', 'São Paulo', 'Rua da Educação, 1000', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Indústria Têxtil Ltda', 'Moda que transforma vidas', 'No', '98765432000101', 'Brasil', 'São Paulo', 'São Paulo', 'Av. das Indústrias, 2000', 'MEMBER', 'CSV', 'ACTIVE'),
('Tech Solutions', 'Soluções tecnológicas para seu negócio', 'Yes', '87654321000112', 'Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Rua da Tecnologia, 3000', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Culinária Caseira', 'O sabor que você procura', 'No', '76543210000123', 'Brasil', 'Minas Gerais', 'Belo Horizonte', 'Av. dos Sabores, 4000', 'EXPIRED', 'CSV', 'ACTIVE'),
('Saúde Integral', 'Cuidando de você por completo', 'Yes', '65432100000134', 'Brasil', 'São Paulo', 'Campinas', 'Rua da Saúde, 5000', 'MEMBER', 'MANUAL', 'INACTIVE'),
('Construções S/A', 'Construindo o futuro com qualidade', 'No', '54321000000145', 'Brasil', 'Rio Grande do Sul', 'Porto Alegre', 'Av. da Construção, 6000', 'MEMBER', 'CSV', 'ACTIVE'),
('Farmácia Popular', 'Medicamentos de qualidade a preços acessíveis', 'Yes', '43210000000156', 'Brasil', 'Rio de Janeiro', 'Niterói', 'Rua da Farmácia, 7000', 'INACTIVE', 'MANUAL', 'ACTIVE'),
('Energia Renovável Ltda', 'Energia limpa para um mundo sustentável', 'No', '32100000000167', 'Brasil', 'São Paulo', 'São Paulo', 'Av. da Energia, 8000', 'MEMBER', 'CSV', 'ACTIVE'),
('Fashion Store', 'Estilo e tendência para todos os estilos', 'Yes', '21000000000178', 'Brasil', 'Minas Gerais', 'Belo Horizonte', 'Rua da Moda, 10000', 'EXPIRED', 'MANUAL', 'INACTIVE'),
('Tecnologia Futura', 'Inovação que impulsiona seu negócio', 'No', '10000000000189', 'Brasil', 'São Paulo', 'Campinas', 'Av. da Tecnologia, 9000', 'MEMBER', 'CSV', 'ACTIVE'),
('Educação Digital', 'Aprendizado flexível e acessível', 'Yes', '11111111000101', 'Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Rua da Educação, 8000', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Bem-Estar & Saúde', 'Seu bem-estar é nossa prioridade', 'No', '22222222000112', 'Brasil', 'Paraná', 'Curitiba', 'Av. do Bem-Estar, 7000', 'INACTIVE', 'CSV', 'ACTIVE'),
('Agronegócio Brasileiro', 'Alimentando o mundo com excelência', 'Yes', '33333333000123', 'Brasil', 'São Paulo', 'São Paulo', 'Av. do Agronegócio, 6000', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Software Solutions', 'Soluções eficientes para seus desafios', 'No', '44444444000134', 'Brasil', 'Minas Gerais', 'Uberlândia', 'Rua do Software, 8000', 'EXPIRED', 'CSV', 'ACTIVE'),
('AutoMecânica 2000', 'Qualidade e confiança em cada reparo', 'Yes', '55555555000145', 'Brasil', 'São Paulo', 'Campinas', 'Av. Automotiva, 9000', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Saúde & Bem-Estar', 'Promovendo uma vida saudável', 'No', '66666666000156', 'Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Rua da Saúde, 10000', 'MEMBER', 'CSV', 'INACTIVE'),
('Construções Modernas', 'Construindo o futuro com inovação', 'Yes', '77777777000167', 'Brasil', 'Minas Gerais', 'Belo Horizonte', 'Av. da Construção, 8000', 'INACTIVE', 'MANUAL', 'ACTIVE'),
('Moda Estilosa', 'Estilo que reflete sua personalidade', 'No', '88888888000178', 'Brasil', 'São Paulo', 'São Paulo', 'Av. da Moda, 9000', 'MEMBER', 'CSV', 'ACTIVE'),
('Gastronomia Deliciosa', 'Sabor que conquista paladares', 'Yes', '99999999000189', 'Brasil', 'Rio de Janeiro', 'Niterói', 'Rua da Gastronomia, 5000', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Tecnologia Inovadora', 'Inovação que transforma sua realidade', 'No', '10101010000190', 'Brasil', 'Paraná', 'Curitiba', 'Av. da Tecnologia, 7000', 'EXPIRED', 'CSV', 'ACTIVE'),
('Educação de Qualidade', 'Conhecimento que faz a diferença', 'Yes', '20202020000101', 'Brasil', 'São Paulo', 'São Paulo', 'Rua da Educação, 11000', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Saúde & Harmonia', 'Equilíbrio para o seu corpo e mente', 'No', '30303030000112', 'Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Av. da Saúde, 8000', 'MEMBER', 'CSV', 'INACTIVE'),
('Construções Inteligentes', 'Inovação em cada projeto', 'Yes', '40404040000123', 'Brasil', 'Minas Gerais', 'Belo Horizonte', 'Rua da Construção, 10000', 'INACTIVE', 'MANUAL', 'ACTIVE'),
('Beleza & Estilo', 'Respeitando sua beleza única', 'No', '50505050000134', 'Brasil', 'São Paulo', 'Campinas', 'Av. da Beleza, 7000', 'MEMBER', 'CSV', 'ACTIVE'),
('Gastronomia Gourmet', 'Sabor e qualidade em cada prato', 'Yes', '60606060000145', 'Brasil', 'Rio de Janeiro', 'Niterói', 'Rua da Gastronomia, 5000', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Tecnologia Avançada', 'Inovação que impulsiona seu negócio', 'No', '70707070000156', 'Brasil', 'Paraná', 'Curitiba', 'Av. da Tecnologia, 8000', 'EXPIRED', 'CSV', 'ACTIVE'),
('Educação Moderna', 'Transformando o aprendizado em oportunidades', 'Yes', '80808080000167', 'Brasil', 'São Paulo', 'São Paulo', 'Rua da Educação, 10000', 'MEMBER', 'MANUAL', 'ACTIVE'),
('Consultoria Empresarial', 'Soluções inteligentes para seu negócio', 'No', '90909090000178', 'Brasil', 'Minas Gerais', 'Uberlândia', 'Av. da Consultoria, 6000', 'MEMBER', 'CSV', 'INACTIVE'),
('Automotiva Nacional', 'Qualidade e confiança em cada veículo', 'Yes', '01010101000189', 'Brasil', 'São Paulo', 'Campinas', 'Av. Automotiva, 9000', 'INACTIVE', 'MANUAL', 'ACTIVE'),
('Saúde & Bem-Estar', 'Promovendo uma vida saudável', 'No', '11223344000190', 'Brasil', 'Rio de Janeiro', 'Rio de Janeiro', 'Rua da Saúde, 10000', 'MEMBER', 'CSV', 'ACTIVE'),
('Construções Modernas', 'Construindo o futuro com inovação', 'Yes', '22334455000101', 'Brasil', 'Minas Gerais', 'Belo Horizonte', 'Av. da Construção, 8000', 'MEMBER', 'MANUAL', 'ACTIVE');





INSERT INTO user (company_id, email, password, name, role, membership_type, ingestion_operation, status)
VALUES
(1, 'admin@inovatech.com', 'hashed_password_123', 'Admin InovaTech', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(1, 'user1@inovatech.com', 'hashed_password_456', 'User InovaTech', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(2, 'user2@alimentos.com', 'hashed_password_789', 'User Alimentos', 'USER', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(2, 'user3@alimentos.com', 'hashed_password_012', 'User Alimentos', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(3, 'admin@autopecas2000.com', 'hashed_password_345', 'Admin AutoPeças 2000', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(3, 'user4@autopecas2000.com', 'hashed_password_678', 'User AutoPeças 2000', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(4, 'admin@consultoria.com', 'hashed_password_901', 'Admin Consultoria Empresarial Ltda', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(4, 'user5@consultoria.com', 'hashed_password_234', 'User Consultoria Empresarial Ltda', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(5, 'admin@construcoesrapidas.com', 'hashed_password_567', 'Admin Construções Rápidas', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(5, 'user6@construcoesrapidas.com', 'hashed_password_890', 'User Construções Rápidas', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(6, 'admin@farmaciacentral.com', 'hashed_password_123', 'Admin Farmácia Central', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(6, 'user7@farmaciacentral.com', 'hashed_password_456', 'User Farmácia Central', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(7, 'admin@energiasolar.com', 'hashed_password_789', 'Admin Energia Solar Ltda', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(7, 'user8@energiasolar.com', 'hashed_password_012', 'User Energia Solar Ltda', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(8, 'admin@modajovem.com', 'hashed_password_345', 'Admin Moda Jovem', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(8, 'user9@modajovem.com', 'hashed_password_678', 'User Moda Jovem', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(9, 'admin@tecnologiaavancada.com', 'hashed_password_901', 'Admin Tecnologia Avançada S.A.', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(9, 'user10@tecnologiaavancada.com', 'hashed_password_234', 'User Tecnologia Avançada S.A.', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(10, 'admin@educacaointeligente.com', 'hashed_password_567', 'Admin Educação Inteligente', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(10, 'user11@educacaointeligente.com', 'hashed_password_890', 'User Educação Inteligente', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(11, 'admin@belezanatural.com', 'hashed_password_123', 'Admin Beleza Natural', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(11, 'user12@belezanatural.com', 'hashed_password_456', 'User Beleza Natural', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(12, 'admin@agriculturamoderna.com', 'hashed_password_789', 'Admin Agricultura Moderna', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(12, 'user13@agriculturamoderna.com', 'hashed_password_012', 'User Agricultura Moderna', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(13, 'admin@tecnologiainformacao.com', 'hashed_password_345', 'Admin Tecnologia da Informação Ltda', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(13, 'user14@tecnologiainformacao.com', 'hashed_password_678', 'User Tecnologia da Informação Ltda', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(14, 'admin@automotivanacional.com', 'hashed_password_901', 'Admin Automotiva Nacional', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(14, 'user15@automotivanacional.com', 'hashed_password_234', 'User Automotiva Nacional', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(15, 'admin@saudeemfoco.com', 'hashed_password_567', 'Admin Saúde em Foco', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(15, 'user16@saudeemfoco.com', 'hashed_password_890', 'User Saúde em Foco', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(16, 'admin@construcoessustentaveis.com', 'hashed_password_123', 'Admin Construções Sustentáveis', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(16, 'user17@construcoessustentaveis.com', 'hashed_password_456', 'User Construções Sustentáveis', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(17, 'admin@modafashion.com', 'hashed_password_789', 'Admin Moda Fashion', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(17, 'user18@modafashion.com', 'hashed_password_012', 'User Moda Fashion', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(18, 'admin@gastronomiagourmet.com', 'hashed_password_345', 'Admin Gastronomia Gourmet', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(18, 'user19@gastronomiagourmet.com', 'hashed_password_678', 'User Gastronomia Gourmet', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(19, 'admin@tecnologiaaplicada.com', 'hashed_password_901', 'Admin Tecnologia Aplicada', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(19, 'user20@tecnologiaaplicada.com', 'hashed_password_234', 'User Tecnologia Aplicada', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(20, 'admin@educacaomoderna.com', 'hashed_password_567', 'Admin Educação Moderna', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(20, 'user21@educacaomoderna.com', 'hashed_password_890', 'User Educação Moderna', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(21, 'admin@industriatextil.com', 'hashed_password_123', 'Admin Indústria Têxtil Ltda', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(21, 'user22@industriatextil.com', 'hashed_password_456', 'User Indústria Têxtil Ltda', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(22, 'admin@techsolutions.com', 'hashed_password_789', 'Admin Tech Solutions', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(22, 'user23@techsolutions.com', 'hashed_password_012', 'User Tech Solutions', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(23, 'admin@culinariacaseira.com', 'hashed_password_345', 'Admin Culinária Caseira', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(23, 'user24@culinariacaseira.com', 'hashed_password_678', 'User Culinária Caseira', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(24, 'admin@saudeintegral.com', 'hashed_password_901', 'Admin Saúde Integral', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(24, 'user25@saudeintegral.com', 'hashed_password_234', 'User Saúde Integral', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(25, 'admin@construcoessa.com', 'hashed_password_567', 'Admin Construções S/A', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(25, 'user26@construcoessa.com', 'hashed_password_890', 'User Construções S/A', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(26, 'admin@farmaciapopular.com', 'hashed_password_123', 'Admin Farmácia Popular', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(26, 'user27@farmaciapopular.com', 'hashed_password_456', 'User Farmácia Popular', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(27, 'admin@energiarenovavel.com', 'hashed_password_789', 'Admin Energia Renovável Ltda', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(27, 'user28@energiarenovavel.com', 'hashed_password_012', 'User Energia Renovável Ltda', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(28, 'admin@fashionstore.com', 'hashed_password_345', 'Admin Fashion Store', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(28, 'user29@fashionstore.com', 'hashed_password_678', 'User Fashion Store', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(29, 'admin@tecnologiafutura.com', 'hashed_password_901', 'Admin Tecnologia Futura', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(29, 'user30@tecnologiafutura.com', 'hashed_password_234', 'User Tecnologia Futura', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(30, 'admin@educacaodigital.com', 'hashed_password_567', 'Admin Educação Digital', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(30, 'user31@educacaodigital.com', 'hashed_password_890', 'User Educação Digital', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(31, 'admin@bemestaresaude.com', 'hashed_password_123', 'Admin Bem-Estar & Saúde', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(31, 'user32@bemestaresaude.com', 'hashed_password_456', 'User Bem-Estar & Saúde', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(32, 'admin@agronegociobrasileiro.com', 'hashed_password_789', 'Admin Agronegócio Brasileiro', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(32, 'user33@agronegociobrasileiro.com', 'hashed_password_012', 'User Agronegócio Brasileiro', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(33, 'admin@softwaresolutions.com', 'hashed_password_345', 'Admin Software Solutions', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(33, 'user34@softwaresolutions.com', 'hashed_password_678', 'User Software Solutions', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(34, 'admin@automecanica2000.com', 'hashed_password_901', 'Admin AutoMecânica 2000', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(34, 'user35@automecanica2000.com', 'hashed_password_234', 'User AutoMecânica 2000', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(35, 'admin@saudebemestar.com', 'hashed_password_567', 'Admin Saúde & Bem-Estar', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(35, 'user36@saudebemestar.com', 'hashed_password_890', 'User Saúde & Bem-Estar', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(36, 'admin@construcoesmodernas.com', 'hashed_password_123', 'Admin Construções Modernas', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(36, 'user37@construcoesmodernas.com', 'hashed_password_456', 'User Construções Modernas', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(37, 'admin@modaestilosa.com', 'hashed_password_789', 'Admin Moda Estilosa', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(37, 'user38@modaestilosa.com', 'hashed_password_012', 'User Moda Estilosa', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(38, 'admin@gastronomiadeliciosa.com', 'hashed_password_345', 'Admin Gastronomia Deliciosa', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(38, 'user39@gastronomiadeliciosa.com', 'hashed_password_678', 'User Gastronomia Deliciosa', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(39, 'admin@tecnologiainovadora.com', 'hashed_password_901', 'Admin Tecnologia Inovadora', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(39, 'user40@tecnologiainovadora.com', 'hashed_password_234', 'User Tecnologia Inovadora', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(40, 'admin@educacaodequalidade.com', 'hashed_password_567', 'Admin Educação de Qualidade', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(40, 'user41@educacaodequalidade.com', 'hashed_password_890', 'User Educação de Qualidade', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(41, 'admin@saudeeharmonia.com', 'hashed_password_123', 'Admin Saúde & Harmonia', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(41, 'user42@saudeeharmonia.com', 'hashed_password_456', 'User Saúde & Harmonia', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(42, 'admin@construcoesinteligentes.com', 'hashed_password_789', 'Admin Construções Inteligentes', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(42, 'user43@construcoesinteligentes.com', 'hashed_password_012', 'User Construções Inteligentes', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(43, 'admin@belezaestilo.com', 'hashed_password_345', 'Admin Beleza & Estilo', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(43, 'user44@belezaestilo.com', 'hashed_password_678', 'User Beleza & Estilo', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(44, 'admin@gastronomiagourmet2.com', 'hashed_password_901', 'Admin Gastronomia Gourmet', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(44, 'user45@gastronomiagourmet2.com', 'hashed_password_234', 'User Gastronomia Gourmet', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(45, 'admin@tecnologiaavancada2.com', 'hashed_password_567', 'Admin Tecnologia Avançada', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(45, 'user46@tecnologiaavancada2.com', 'hashed_password_890', 'User Tecnologia Avançada', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(46, 'admin@educacaomoderna2.com', 'hashed_password_123', 'Admin Educação Moderna', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(46, 'user47@educacaomoderna2.com', 'hashed_password_456', 'User Educação Moderna', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(47, 'admin@consultoriaempresarial2.com', 'hashed_password_789', 'Admin Consultoria Empresarial', 'ADM', 'PRINCIPAL', 'MANUAL', 'INACTIVE'),
(47, 'user48@consultoriaempresarial2.com', 'hashed_password_012', 'User Consultoria Empresarial', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE'),
(48, 'admin@automotivanacional2.com', 'hashed_password_345', 'Admin Automotiva Nacional', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(48, 'user49@automotivanacional2.com', 'hashed_password_678', 'User Automotiva Nacional', 'USER', 'WORLDWIDE', 'CSV', 'INACTIVE'),
(49, 'admin@saudeefitness2.com', 'hashed_password_901', 'Admin Saúde & Fitness', 'ADM', 'PRINCIPAL', 'MANUAL', 'ACTIVE'),
(49, 'user50@saudeefitness2.com', 'hashed_password_234', 'User Saúde & Fitness', 'USER', 'WORLDWIDE', 'CSV', 'ACTIVE');




INSERT INTO opn_track (name, ingestion_operation, status) VALUES
('Cloud Service', 'MANUAL', 'ACTIVE'),
('Cloud Sell', 'MANUAL', 'ACTIVE'),
('Cloud Build & Service', 'MANUAL', 'ACTIVE'),
('License and Hardware', 'MANUAL', 'ACTIVE');


INSERT INTO service_expertise (name, description, ingestion_operation, status) VALUES
               ('Oracle Cloud Platform Integration', 'Expertise in integrating applications and services using Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Oracle Cloud Platform Business Analytics', 'Expertise in analytics and data management using Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Oracle Cloud Platform Application Development', 'Expertise in developing applications on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Oracle Cloud Platform Data Management', 'Expertise in managing and integrating data on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Oracle Cloud Platform Security', 'Expertise in implementing security measures on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Oracle Cloud Platform Content Management', 'Expertise in managing content and experiences on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Oracle Cloud Platform Systems Management', 'Expertise in managing systems on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: AI / Machine Learning', 'Expertise in AI and machine learning solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Database to Oracle Cloud', 'Expertise in migrating and managing Oracle databases on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Oracle Cloud Hyperion/Essbase', 'Expertise in Hyperion/Essbase solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Dev Ops on Oracle Cloud', 'Expertise in DevOps practices on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Cloud Native Applications on Oracle Cloud', 'Expertise in developing cloud-native applications on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Oracle Cloud VMware Solution', 'Expertise in VMware solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Oracle Cloud Platform AI/ML', 'Expertise in AI and machine learning solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('Oracle Cloud Platform Blockchain', 'Expertise in blockchain solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Integration', 'Expertise in integrating applications and services using Oracle Integration', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Business Intelligence', 'Expertise in business intelligence solutions using Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Content and Experience', 'Expertise in content and experience management on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Identity and Access Management', 'Expertise in identity and access management on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Management Cloud', 'Expertise in management solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Autonomous Database', 'Expertise in autonomous database solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Cloud Infrastructure', 'Expertise in infrastructure solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Integration Cloud', 'Expertise in integration solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Process Cloud', 'Expertise in process automation on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle API Platform', 'Expertise in API management on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle SOA Cloud', 'Expertise in service-oriented architecture solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Cloud Management', 'Expertise in cloud management solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Database Cloud', 'Expertise in database solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Big Data Cloud', 'Expertise in big data solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Event Hub Cloud', 'Expertise in event hub solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Messaging Cloud', 'Expertise in messaging solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Analytics Cloud', 'Expertise in analytics solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Data Integration Cloud', 'Expertise in data integration solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Data Lake Cloud', 'Expertise in data lake solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Data Science Cloud', 'Expertise in data science solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Machine Learning Cloud', 'Expertise in machine learning solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle AI Cloud', 'Expertise in AI solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Blockchain Cloud', 'Expertise in blockchain solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Internet of Things Cloud', 'Expertise in IoT solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Container Cloud', 'Expertise in container solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Kubernetes Cloud', 'Expertise in Kubernetes solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Function Cloud', 'Expertise in function solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Serverless Cloud', 'Expertise in serverless solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle API Gateway Cloud', 'Expertise in API gateway solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Data Gateway Cloud', 'Expertise in data gateway solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE'),
               ('CSSE: Oracle Workflow Cloud', 'Expertise in workflow solutions on Oracle Cloud Platform', 'MANUAL', 'ACTIVE');





INSERT INTO certification (name, description, life_time_month, ingestion_operation) VALUES
                    ('Oracle Cloud Infrastructure Integration Cloud 2020 Associate', 'Certification for integrating cloud infrastructure on Oracle Cloud', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Application Integration 2020 Associate', 'Certification for application integration on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Developer 2020 Associate', 'Certification for developing infrastructure on Oracle Cloud', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Data Management 2020 Associate', 'Certification for managing data on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Data Integration 2020 Associate', 'Certification for integrating data on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Data Warehousing 2020 Associate', 'Certification for data warehousing on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Security Operations 2020 Associate', 'Certification for security operations on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Security 2020 Associate', 'Certification for implementing security on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Identity and Access Management 2020 Associate', 'Certification for identity and access management on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Content and Experience 2020 Associate', 'Certification for managing content and experience on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Systems Management 2020 Associate', 'Certification for managing systems on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Foundations 2020 Associate', 'Certification for foundational skills on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure AI/ML Associate', 'Certification for AI/ML on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud VMware Solution 2020 Associate', 'Certification for VMware solutions on Oracle Cloud', 24, 'MANUAL'),
                    ('Oracle Cloud Platform AI/ML 2020 Associate', 'Certification for AI/ML on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Blockchain 2020 Associate', 'Certification for blockchain solutions on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('CSSE: Oracle Database to Oracle Cloud 2020 Associate', 'Certification for migrating databases to Oracle Cloud', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Application Development 2020 Associate', 'Certification for application development on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Data Management 2021 Associate', 'Certification for managing data on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Security 2020 Associate', 'Certification for implementing security on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Hyperion/Essbase 2020 Associate', 'Certification for Hyperion/Essbase solutions on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Dev Ops on Oracle Cloud 2020 Associate', 'Certification for DevOps practices on Oracle Cloud', 24, 'MANUAL'),
                    ('Cloud Native Applications on Oracle Cloud 2020 Associate', 'Certification for developing cloud-native applications on Oracle Cloud', 24, 'MANUAL'),
                    ('Oracle Database Cloud Service 2020 Associate', 'Certification for managing databases on Oracle Cloud', 24, 'MANUAL'),
                    ('Oracle E-Business Suite Applications to Oracle Cloud 2020 Associate', 'Certification for migrating E-Business Suite applications to Oracle Cloud', 24, 'MANUAL'),
                    ('JD Edwards Applications to Oracle Cloud 2020 Associate', 'Certification for migrating JD Edwards applications to Oracle Cloud', 24, 'MANUAL'),
                    ('SAP Applications to Oracle Cloud 2020 Associate', 'Certification for migrating SAP applications to Oracle Cloud', 24, 'MANUAL'),
                    ('Microsoft Applications to Oracle Cloud 2020 Associate', 'Certification for migrating Microsoft applications to Oracle Cloud', 24, 'MANUAL'),
                    ('Infor Applications to Oracle Cloud 2020 Associate', 'Certification for migrating Infor applications to Oracle Cloud', 24, 'MANUAL'),
                    ('PeopleSoft Applications to Oracle Cloud 2020 Associate', 'Certification for migrating PeopleSoft applications to Oracle Cloud', 24, 'MANUAL'),
                    ('Siebel Applications to Oracle Cloud 2020 Associate', 'Certification for migrating Siebel applications to Oracle Cloud', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Integration Cloud 2021 Associate', 'Certification for integrating cloud infrastructure on Oracle Cloud', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Application Integration 2021 Associate', 'Certification for application integration on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Developer 2021 Associate', 'Certification for developing infrastructure on Oracle Cloud', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Data Management 2022 Associate', 'Certification for managing data on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Data Integration 2021 Associate', 'Certification for integrating data on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Data Warehousing 2021 Associate', 'Certification for data warehousing on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Security Operations 2021 Associate', 'Certification for security operations on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Security 2021 Associate', 'Certification for implementing security on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Identity and Access Management 2021 Associate', 'Certification for identity and access management on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Content and Experience 2021 Associate', 'Certification for managing content and experience on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Systems Management 2021 Associate', 'Certification for managing systems on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure Foundations 2021 Associate', 'Certification for foundational skills on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud Infrastructure AI/ML Associate 2021', 'Certification for AI/ML on Oracle Cloud Infrastructure', 24, 'MANUAL'),
                    ('Oracle Cloud VMware Solution 2021 Associate', 'Certification for VMware solutions on Oracle Cloud', 24, 'MANUAL'),
                    ('Oracle Cloud Platform AI/ML 2021 Associate', 'Certification for AI/ML on Oracle Cloud Platform', 24, 'MANUAL'),
                    ('Oracle Cloud Platform Blockchain 2021 Associate', 'Certification for blockchain solutions on Oracle Cloud Platform', 24, 'MANUAL');



INSERT INTO workload (name, description, ingestion_operation, status) VALUES
      ('Data Warehousing', 'Armazenamento e processamento de grandes volumes de dados para análise de negócios', 'MANUAL', 'ACTIVE'),
      ('Batch Processing', 'Processamento em lote de grandes volumes de dados para análise e relatórios periódicos', 'MANUAL', 'ACTIVE'),
      ('Data Migration', 'Migração de dados entre sistemas ou plataformas para consolidação ou atualização', 'MANUAL', 'ACTIVE'),
      ('Streaming Analytics', 'Análise em tempo real de fluxos contínuos de dados para detecção de padrões e tendências', 'MANUAL', 'ACTIVE'),
      ('Data Archiving', 'Arquivamento de dados históricos para armazenamento a longo prazo e conformidade regulatória', 'MANUAL', 'ACTIVE'),
      ('Data Replication', 'Replicação de dados entre bancos de dados para alta disponibilidade e recuperação de desastres', 'MANUAL', 'ACTIVE'),
      ('Data Masking', 'Ocultação de dados confidenciais para proteger a privacidade e garantir a conformidade', 'MANUAL', 'ACTIVE'),
      ('Data Compression', 'Compressão de dados para reduzir o espaço de armazenamento e otimizar o desempenho', 'MANUAL', 'ACTIVE'),
      ('Data Deduplication', 'Remoção de duplicatas de dados para economizar espaço de armazenamento e melhorar a eficiência', 'MANUAL', 'ACTIVE'),
      ('Data Transformation', 'Transformação de dados para prepará-los para análise ou integração em diferentes sistemas', 'MANUAL', 'ACTIVE'),
      ('Data Mining', 'Exploração de grandes conjuntos de dados para descobrir padrões e insights ocultos', 'MANUAL', 'ACTIVE'),
      ('Data Lake Management', 'Gerenciamento de data lakes para armazenamento e análise de dados brutos em escala', 'MANUAL', 'ACTIVE'),
      ('Data Warehouse Optimization', 'Otimização de data warehouses para melhorar o desempenho e a eficiência das consultas', 'MANUAL', 'ACTIVE'),
      ('Data Virtualization', 'Virtualização de dados para integrar e acessar dados distribuídos de forma transparente', 'MANUAL', 'ACTIVE'),
      ('Data Cataloging', 'Catalogação de metadados para facilitar a descoberta e o uso de conjuntos de dados', 'MANUAL', 'ACTIVE'),
      ('Data Governance Framework', 'Implementação de políticas e processos para garantir a qualidade e a integridade dos dados', 'MANUAL', 'ACTIVE'),
      ('Data Loss Prevention', 'Prevenção de perda de dados por meio de controles e políticas de segurança proativas', 'MANUAL', 'ACTIVE'),
      ('Data Lake Security', 'Implementação de controles de segurança para proteger dados em data lakes contra ameaças internas e externas', 'MANUAL', 'ACTIVE'),
      ('Data Ethics Compliance', 'Adoção de práticas éticas de dados para garantir o uso responsável e ético dos dados', 'MANUAL', 'ACTIVE'),
      ('Data Anonymization', 'Anonimização de dados para remover identificadores pessoais e proteger a privacidade dos indivíduos', 'MANUAL', 'ACTIVE');
